name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact-name: ${{ steps.set-artifact-name.outputs.artifact-name }}

    steps:
      - name: copy code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Set artifact name output
        id: set-artifact-name
        run: echo "artifact-name=build-output" >> "$GITHUB_OUTPUT"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact-name.outputs.artifact-name }}
          path: dist/

  inspect:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Print artifact name output
        run: echo "Artifact name is ${{ needs.build.outputs.artifact-name }}"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: dist/

      - name: List downloaded files
        run: ls -R dist/
